### ISSUE TITLE
Replace the ontroller module hardware - AFF A700s

### ISSUE THREAD

**Issue by jbeermannetapp** [NetAppDocs/ontap-systems#95] opened 2022-07-28 13:12 UTC
Page: [Replace the ontroller module hardware - AFF A700s](https://docs.netapp.com/us-en/ontap-systems/a700s/controller-replace-move-hardware.html)

fix the typo in the title

**Comment by thrisun** [comment] 2022-08-10 17:12
This was addressed by Tim McGue. I already mentioned this to Marty and Doug on 8/2.

**Comment by jbeermannetapp** [comment] 2022-08-10 20:34
I don’t see a change in the document, does it take time to propagate?

Jim Beerman
TSE4

NetApp
***@***.******@***.***>
1-888-463-8277 opt 2, opt 9 x9847221

***@***.***

[A close up of a logo  Description automatically generated]


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

My normal working hours are Monday-to-Friday, 7 a.m. - 4 p.m. ET.

Everyone at NetApp is committed to the highest level of customer satisfaction. If at any time you have
any concerns or comments about our support please contact my manager, Bobby Franke, at 919-476-5976, or email him at ***@***.******@***.***>


For technical assistance on a new or existing case, please call:
US & Canada 888-4-NETAPP
EMEA/Europe  00-800-44-NETAPP
Asia/Pacific  800-8008-0800

**Comment by thrisun** [comment] 2022-08-10 23:18
Doug can you take a look at this again?

**Comment by dougthomp** [comment] 2022-08-10 23:21
Looking now.

**Comment by thrisun** [comment] 2022-08-10 23:21
![image](https://user-images.githubusercontent.com/30325635/184039546-23f69ddd-ca3a-4120-a013-a9a89c17fadd.png)

**Comment by jbeermannetapp** [comment] 2022-08-11 00:24
Hmm, my doc change had to do with converting switch less to switched.
I may have had another with the a700s.

________________________________

**Comment by netapp-martyh** [comment] 2022-08-11 18:56
The public repo is building now with the typo fix.

**Comment by dougthomp** [comment] 2022-08-11 20:48
Confirmed changes are appearing.

**Comment by netapp-martyh** [comment] 2022-12-16 16:54
Looks like this is resolved.

**Closed by netapp-martyh** 2022-12-16 16:54 UTC
Labels: documentation
