### ISSUE TITLE
MCC node replacement: Steps 1 and 2 describe the same command

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap-systems#17] opened 2021-05-28 08:44 UTC
Page: [Move non-root aggregates and NAS data LIFs owned by node1 from node2 to node3](https://docs.netapp.com/us-en/ontap-systems/upgrade-arl-auto-app/moving_non-root_aggregates_and_nas_data_lifs_owned_by_node1_from_node2_to_node3.html)

Step 1 starts with:
> Resume the relocation operation by using the following command:
>
> `system controller replace resume`
> ...

Step 2 starts with:
> Resume the relocation operation by using the following command:
> 
> `system controller replace resume`

Step three then contains the same info as step 1.

I think one of these is redundant, either step 1, or step 2+3

**Comment by netapp-pcarriga** [comment] 2022-03-21 18:09
@darkstar Hi Michael, apologies for the delay in letting you know that this issue has been resolved. 
To remove confusion that step 2 is a duplicate of step 1, [we've added an intervening verification step](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html). 
Thanks again for your feedback and helping us improve our customer documentation!

**Closed by netapp-pcarriga** 2022-03-21 18:09 UTC
Labels: documentation
